services:
  web:
    build: .
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.web.loadbalancer.server.port: 3000
      traefik.http.services.web.loadbalancer.server.scheme: http
      traefik.http.routers.web.rule: HostRegexp(`^(www\.)?reversed-r\.dev`)
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.tls.certResolver: leresolver
      traefik.http.routers.web.service: web
      # traefik.http.routers.web.rule: HostRegexp(`{host:.+}`)
      # traefik.http.routers.web.priority: 1
      # traefik.http.routers.web.tls: true
      # traefik.http.routers.web.middlewares: redirectall
      # traefik.http.middlewares.redirectall.redirectregex.regex: .*
      # traefik.http.middlewares.redirectall.redirectregex.replacement: https://reversed-r.dev
    networks:
      - default
      - traefik
networks:
  default:
  traefik:
    name: traefik
    external: true
