services:
  website:
    build: .
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.website.loadbalancer.server.port: 3000
      traefik.http.services.website.loadbalancer.server.scheme: http
      traefik.http.routers.website.rule: Host(`reversed-r.dev`)
      traefik.http.routers.website.entrypoints: websecure,web
      traefik.http.routers.website.tls.certResolver: leresolver
      traefik.http.routers.website.service: website
      # traefik.http.routers.website.rule: HostRegexp(`{host:.+}`)
      # traefik.http.routers.website.priority: 1
      # traefik.http.routers.website.tls: true
      # traefik.http.routers.website.middlewares: redirectall
      # traefik.http.middlewares.redirectall.redirectregex.regex: .*
      # traefik.http.middlewares.redirectall.redirectregex.replacement: https://reversed-r.dev
    networks:
      - traefik
networks:
  traefik:
    name: traefik
    external: true
